services:
  hello-english: &hello
    image: localhost/hello:latest
    entrypoint: ["hello", "--greeting", "Hello"]
    profiles:
      - services

  hello-italian:
    <<: *hello
    entrypoint: ["hello", "--greeting", "Ciao"]
    profiles:
      - services

  hello-spanish:
    <<: *hello
    entrypoint: ["hello", "--greeting", "Hola"]
    profiles:
      - programs
      - services
