name: "NGI Project"
description: "User story for an NGI project."
title: "NGI Project: PROJECT_NAME"
labels: ["User story", "nix-forge"]
body:
  - type: "textarea"
    id: tasks
    attributes:
      label: "Tasks"
      description: "Create a sub-issue for each task by clicking the links below."
      value: |
        - [ ] [PROJECT_NAME: Create a package recipe](https://github.com/ngi-nix/forge/issues/new?title=PROJECT_NAME%3A+Create+a+package+recipe&labels[]=nix-forge)
        - [ ] [PROJECT_NAME: Create an application recipe](https://github.com/ngi-nix/forge/issues/new?title=PROJECT_NAME%3A+Create+an+application+recipe&labels[]=nix-forge)
        - [ ] [PROJECT_NAME: Announce a packaged project](https://github.com/ngi-nix/forge/issues/new?title=PROJECT_NAME%3A+Announce+a+packaged+project&labels[]=nix-forge)
