name: Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
    inputs:
      pr_number:
        required: false
        type: string

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      # - name: Get more storage space
      #   uses: wimpysworld/nothing-but-nix@main

      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      - uses: cachix/cachix-action@v16
        with:
          name: ngi-forge
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Run checks
        run: nix flake check --accept-flake-config

  build-preview-ui:
    name: Build UI artifact
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.pr_number != '')

    steps:
      - name: Check out repository
        uses: actions/checkout@v6
        with:
          # Fetches the specific PR branch if manually dispatched, otherwise defaults to standard checkout
          ref: ${{ github.event_name == 'workflow_dispatch' && format('refs/pull/{0}/head', github.event.inputs.pr_number) || '' }}

      - name: Save PR context
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "${{ github.event.inputs.pr_number }}" > pr-number.txt
            git rev-parse HEAD > pr-rev.txt
          else
            echo "${{ github.event.pull_request.number }}" > pr-number.txt
            echo "${{ github.event.pull_request.head.sha }}" > pr-rev.txt
          fi

      - name: Install Nix
        uses: cachix/install-nix-action@19effe9fe722874e6d46dd7182e4b8b7a43c4a99 # v31.10.0

      # NOTE: no auth token, so read-only. because we will not be pushing anything here
      - uses: cachix/cachix-action@v16
        with:
          name: ngi-forge

      - name: Encode version information
        run: |
          set -x
          git log | head -n 100
          commit="$(git rev-parse HEAD)"
          commit=${commit:-master}
          sed -i "s/master/$commit/g" ui/src/Main/Config.elm

      - name: Configure the baseUrl
        run: |
          sed -i "s|:baseUrl|/|g" ui/src/Main/Route.elm
          sed -i "s|<base href=\"/\"|<base href=\"/\"|g" ui/src/index.html

      - name: Build UI
        run: nix build .#_forge-ui --accept-flake-config

      - name: Resolve Nix Symlink
        run: |
          mkdir -p deploy_dist
          cp -rL result/. deploy_dist/

      - name: Upload preview ui
        uses: actions/upload-artifact@v7
        with:
          name: ui-build-preview
          path: |
            deploy_dist/
            pr-number.txt
            pr-rev.txt
          retention-days: 1
